"""empty message

Revision ID: 314df4de2ee7
Revises: c5312781d959
Create Date: 2020-02-27 11:26:28.835750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314df4de2ee7'
down_revision = 'c5312781d959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
